name    'puppet-windows_7zip'
version '0.1.0'
source 'https://github.com/openstack-hyper-v/puppet-windows_7zip.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache License, Version 2.0'
summary 'Retrieves and installs 7zip on the Windows Platform'
description 'Retrieves and installs 7zip on the Windows Platform'
project_page 'https://github.com/openstack-hyper-v/puppet-windows_7zip'
dependency 'joshcooper/powershell'
dependency 'openstack-hyper-v/windows_common'
dependency 'basti1302/windows_path'
dependency 'chocolatey/chocolatey'
